### ISSUE TITLE
No module named 'torch._six'

### ISSUE THREAD

**Issue by mohanrajroboticist** [VincentSch4rf/torchtime#1]
torch has not attribute _six
 https://github.com/pytorch/pytorch/pull/94709
 Please check line 38 in file timeseries.py
 `        if isinstance(root, torch._six.string_classes):
            root = os.path.expanduser(root)`
 
![image](https://github.com/VincentSch4rf/torchtime/assets/86923487/aab17fde-fe57-4a21-b771-590f3be33b8a)

**Comment by mohanrajroboticist** [comment]
Please provide compatible **torch** and **python** version

**Comment by VincentSch4rf** [comment]
Hi @mohanrajroboticist, sorry for not getting back to you earlier. It seems like my notifications settings were properly configured.

With PyTorch 2.0, the `_six` module was finally retired. As the `unicode` type, which was the origin of having to check for multiple types when looking for a string, has been retired since Python 3.8, a replacing this call with `str` is sufficient for modern Python.

I have recently re-started development on this library and have already addressed this issue in the latest patch release (0.1.2).

If you should still be facing issues after the update, please do not hesitate to come back to me.  Now I will receive the notifications, I promise :sweat_smile:
